services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hugo_doctofree_db
      MARIADB_USER: hugo_doctofree_user
      MARIADB_PASSWORD: hugo_doctofree_pwd
    volumes:
      - database_data_doctofree:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data_doctofree:
